export interface Candidate {
  id: string;
  name: string;
  email: string;
  jobId: string;
  interviewer: string;
  date: string;
  round: string;
  mode: string;
  status: "Pending" | "Completed";
}

export const candidateData: Candidate[] = [
  {
    id: "S0001",
    name: "Alice",
    email: "alice@example.com",
    jobId: "J001",
    interviewer: "John Smith",
    date: "2025-01-01",
    round: "Technical",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "S0002",
    name: "Ben",
    email: "ben@example.com",
    jobId: "J002",
    interviewer: "Jane Doe",
    date: "2025-01-01",
    round: "Technical",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "S0003",
    name: "Catherine",
    email: "catherine@example.com",
    jobId: "J003",
    interviewer: "Dr. Xavier",
    date: "2025-01-01",
    round: "HR",
    mode: "Offline",
    status: "Pending",
  },
  {
    id: "S0004",
    name: "Daniel",
    email: "daniel@example.com",
    jobId: "J004",
    interviewer: "Alex Chen",
    date: "2025-02-05",
    round: "Technical",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "S0005",
    name: "Sam",
    email: "sam@example.com",
    jobId: "J005",
    interviewer: "Mira Patel",
    date: "2025-02-05",
    round: "Design",
    mode: "Offline",
    status: "Pending",
  },
  {
    id: "S0006",
    name: "Smith",
    email: "smith@example.com",
    jobId: "J006",
    interviewer: "Rahul Verma",
    date: "2025-02-05",
    round: "Technical",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "S0007",
    name: "Liam",
    email: "liam@example.com",
    jobId: "J007",
    interviewer: "Chris Brown",
    date: "2025-05-22",
    round: "Coding",
    mode: "Offline",
    status: "Pending",
  },
  {
    id: "S0008",
    name: "Ava",
    email: "ava@example.com",
    jobId: "J008",
    interviewer: "Diana Lee",
    date: "2025-05-22",
    round: "Managerial",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "S0009",
    name: "Mia",
    email: "mia@example.com",
    jobId: "J009",
    interviewer: "Albert Kim",
    date: "2025-05-22",
    round: "HR",
    mode: "Offline",
    status: "Pending",
  },
  {
    id: "S0010",
    name: "Ella",
    email: "ella@example.com",
    jobId: "J010",
    interviewer: "Nina Rao",
    date: "2025-06-10",
    round: "System",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "S0011",
    name: "Lucas",
    email: "lucas@example.com",
    jobId: "J011",
    interviewer: "Tom Hardy",
    date: "2025-06-10",
    round: "Frontend",
    mode: "Offline",
    status: "Pending",
  },
  {
    id: "S0012",
    name: "Isabella",
    email: "isabella@example.com",
    jobId: "J012",
    interviewer: "Sophia Lin",
    date: "2025-06-10",
    round: "Documentation",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "S0013",
    name: "James",
    email: "james@example.com",
    jobId: "J013",
    interviewer: "Ravi Kumar",
    date: "2025-06-10",
    round: "Support",
    mode: "Offline",
    status: "Pending",
  },
  {
    id: "S0014",
    name: "Grace",
    email: "grace@example.com",
    jobId: "J014",
    interviewer: "Emma Jones",
    date: "2025-06-10",
    round: "Scrum",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "S0015",
    name: "Noah",
    email: "noah@example.com",
    jobId: "J015",
    interviewer: "Lara Dean",
    date: "2025-06-12",
    round: "DevOps",
    mode: "Online",
    status: "Pending",
  },
  {
    id: "S0016",
    name: "Olivia",
    email: "olivia@example.com",
    jobId: "J016",
    interviewer: "Kevin Hill",
    date: "2025-06-12",
    round: "Cloud",
    mode: "Offline",
    status: "Completed",
  },
  {
    id: "S0017",
    name: "Anakin",
    email: "anakin@example.com",
    jobId: "J017",
    interviewer: "Ken Obi",
    date: "2025-06-18",
    round: "Security",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "S0018",
    name: "Ruby",
    email: "ruby@example.com",
    jobId: "J018",
    interviewer: "Leia Organa",
    date: "2025-06-18",
    round: "Security",
    mode: "Offline",
    status: "Pending",
  },
  {
    id: "S0019",
    name: "Dooku",
    email: "dooku@example.com",
    jobId: "J019",
    interviewer: "Mace Windu",
    date: "2025-06-18",
    round: "Cloud",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "S0020",
    name: "Leia",
    email: "leia@example.com",
    jobId: "J020",
    interviewer: "Yoda Sen",
    date: "2025-06-18",
    round: "Mechanical",
    mode: "Offline",
    status: "Pending",
  },
];
